apiVersion: "v1"
kind: "Service"
metadata:
  name: "yolo-client-deploy-service"
  namespace: "default"
  labels:
    app: "yolo-client-deploy"
spec:
  ports:
  - protocol: "TCP"
    port: 5000
    targetPort: 3000
  selector:
    app: "yolo-client-deploy"
  type: "LoadBalancer"
  loadBalancerIP: ""
